"""initial commit

Revision ID: 0f8ec9eac72e
Revises: bae33ef1b716
Create Date: 2025-06-19 17:14:34.122442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f8ec9eac72e'
down_revision: Union[str, None] = 'bae33ef1b716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'package_type',
               existing_type=postgresql.ENUM('STACKABLE_GOODS', 'NON_STACKABLE_GOODS', 'DANGEROUS_GOODS', 'NON_DANGEROUS_GOODS', 'DANGEROUS_STACKABLE_GOODS', 'DANGEROUS_NON_STACKABLE_GOODS', name='packagetype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'package_type',
               existing_type=postgresql.ENUM('STACKABLE_GOODS', 'NON_STACKABLE_GOODS', 'DANGEROUS_GOODS', 'NON_DANGEROUS_GOODS', 'DANGEROUS_STACKABLE_GOODS', 'DANGEROUS_NON_STACKABLE_GOODS', name='packagetype'),
               nullable=True)
    # ### end Alembic commands ###
