"""is_deleted, tracking number updated

Revision ID: 310f9b32a70b
Revises: eda79e23de06
Create Date: 2025-06-20 16:48:03.523308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310f9b32a70b'
down_revision: Union[str, None] = 'eda79e23de06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('countries', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('currency', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('packages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('packages', 'is_delete')
    op.add_column('payments', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('shipments', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('shipments', 'tracking_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.add_column('status_tracker', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('status_tracker', 'is_deleted')
    op.alter_column('shipments', 'tracking_number',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('shipments', 'is_deleted')
    op.drop_column('payments', 'is_deleted')
    op.add_column('packages', sa.Column('is_delete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('packages', 'is_deleted')
    op.drop_column('currency', 'is_deleted')
    op.drop_column('countries', 'is_deleted')
    op.drop_column('addresses', 'is_deleted')
    # ### end Alembic commands ###
