"""initial commit

Revision ID: 9d0e2d94c5dc
Revises: 0f8ec9eac72e
Create Date: 2025-06-19 17:51:47.761451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d0e2d94c5dc'
down_revision: Union[str, None] = '0f8ec9eac72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'package_type',
               existing_type=postgresql.ENUM('STACKABLE_GOODS', 'NON_STACKABLE_GOODS', 'DANGEROUS_GOODS', 'NON_DANGEROUS_GOODS', 'DANGEROUS_STACKABLE_GOODS', 'DANGEROUS_NON_STACKABLE_GOODS', name='packagetype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'package_type',
               existing_type=postgresql.ENUM('STACKABLE_GOODS', 'NON_STACKABLE_GOODS', 'DANGEROUS_GOODS', 'NON_DANGEROUS_GOODS', 'DANGEROUS_STACKABLE_GOODS', 'DANGEROUS_NON_STACKABLE_GOODS', name='packagetype'),
               nullable=False)
    # ### end Alembic commands ###
