"""initial commit

Revision ID: bae33ef1b716
Revises: 23c0c7e08640
Create Date: 2025-06-19 14:30:51.176839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae33ef1b716'
down_revision: Union[str, None] = '23c0c7e08640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shipments_shipment_status_id_fkey'), 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'shipment_status_id')
    op.add_column('status_tracker', sa.Column('shipment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'status_tracker', 'shipments', ['shipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'status_tracker', type_='foreignkey')
    op.drop_column('status_tracker', 'shipment_id')
    op.add_column('shipments', sa.Column('shipment_status_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('shipments_shipment_status_id_fkey'), 'shipments', 'status_tracker', ['shipment_status_id'], ['id'])
    # ### end Alembic commands ###
