"""is delete boolean added

Revision ID: eda79e23de06
Revises: 9d0e2d94c5dc
Create Date: 2025-06-20 12:52:35.589918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda79e23de06'
down_revision: Union[str, None] = '9d0e2d94c5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'is_delete')
    # ### end Alembic commands ###
